version: "3.9"

services:
  reports_db:
    image: postgres:15
    container_name: reports_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  reports-backend:
    build: .
    container_name: reports_backend
    restart: unless-stopped
    depends_on:
      - reports_db
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  postgres_data:
